"""Strategy base class and data types for plug-and-play Alpaca strategies.

Any strategy that wants to run on Alpaca must implement the Strategy ABC.
The runner handles all execution, risk management, and Alpaca integration.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from sqlalchemy import Engine, text


@dataclass
class Signal:
    """A buy/sell signal generated by a strategy.

    The runner uses these to determine which positions to open.
    Signals should be returned ranked by score (highest first).
    """
    ticker: str
    side: str = "long"          # "long" or "short"
    score: float = 0.0
    angle: float = 0.0
    price: float = 0.0
    entry_date: str = ""        # YYYY-MM-DD
    entry_type: str = ""         # Strategy-specific label (e.g. "A" or "B")


@dataclass
class ExitCheck:
    """Result of checking whether a position should be closed."""
    should_close: bool = False
    reason: str = ""


class Strategy(ABC):
    """Base class for all trading strategies.

    A strategy answers two questions:
    1. What should I buy/sell? (get_signals)
    2. When should I exit a position? (should_exit)

    The runner handles all execution, risk management, and Alpaca integration.
    """

    @abstractmethod
    def get_name(self) -> str:
        """Human-readable strategy name (e.g. 'Golden Cross Rotation')."""
        ...

    @abstractmethod
    def get_signals(self, as_of_date: str, engine: Engine) -> List[Signal]:
        """Generate buy/sell signals for the given date.

        Args:
            as_of_date: Trading date to evaluate (YYYY-MM-DD)
            engine: SQLAlchemy database engine for data access

        Returns:
            List of Signal objects, ranked by score descending.
            Only the top N (up to max_holdings) will be used.
        """
        ...

    @abstractmethod
    def should_exit(self, ticker: str, as_of_date: str,
                    engine: Engine, side: str = "long") -> ExitCheck:
        """Check if an existing position should be closed.

        Args:
            ticker: Stock symbol
            as_of_date: Current trading date
            engine: SQLAlchemy database engine
            side: "long" or "short"

        Returns:
            ExitCheck with should_close=True and reason if position should close.
        """
        ...

    @property
    @abstractmethod
    def max_holdings(self) -> int:
        """Maximum number of positions the strategy can hold at once."""
        ...

    @property
    @abstractmethod
    def sizing_pcts(self) -> List[float]:
        """Position sizing percentages, largest first. Must sum to 1.0."""
        ...


# ── Shared DB Utilities ──────────────────────────────────────────────

def get_all_tickers(engine: Engine) -> List[str]:
    """Get all stock ticker table names from the database."""
    skip = {
        'stock_metadata', 'stock_financials_quarterly', 'stock_financials_yearly',
        'xlb', 'xlc', 'xle', 'xlf', 'xli', 'xlk', 'xlp', 'xlre', 'xlu', 'xlv', 'xly', 'vix',
    }
    with engine.connect() as conn:
        res = conn.execute(text(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"
        ))
        return [row[0] for row in res if row[0] not in skip]
