"""Pluggable Strategy class generated by AI Strategy Builder.

Auto-generated from a session's LLM-produced code. To regenerate, run a
new batch in the AI Strategy Builder and deploy the winner.

The user's strategy code lives in the sibling file `_user_strategy.py`
and is loaded at runtime. Do not edit that file unless you know what
you're doing — re-deploying will overwrite it.
"""
import logging
import sys
import importlib.util
import importlib
from pathlib import Path
from typing import List, Dict, Any

from sqlalchemy import text

from app.services.strategy_base import Strategy, Signal, ExitCheck, get_all_tickers

logger = logging.getLogger(__name__)


# ── Load user strategy from sibling file ─────────────────────────────────
_THIS_DIR = Path(__file__).resolve().parent
_USER_STRATEGY_PATH = _THIS_DIR / "_user_strategy.py"


def _load_user_module():
    """Import the user's strategy module from the sibling file.

    Cached so multiple get_signals() / should_exit() calls don't re-import.
    """
    if "_user_strategy_loaded" not in globals():
        spec = importlib.util.spec_from_file_location("_user_strategy_runtime", str(_USER_STRATEGY_PATH))
        if spec is None or spec.loader is None:
            raise ImportError(f"Could not load user strategy from {_USER_STRATEGY_PATH}")
        mod = importlib.util.module_from_spec(spec)
        sys.modules["_user_strategy_runtime"] = mod
        spec.loader.exec_module(mod)
        globals()["_user_strategy_loaded"] = mod
    return globals()["_user_strategy_loaded"]


class phase3e2e4V20220607(Strategy):
    """phase3-e2e4 — auto-deployed from AI Strategy Builder."""

    def __init__(self):
        super().__init__()
        self._mod = _load_user_module()

    def get_name(self) -> str:
        return "phase3-e2e4"

    @property
    def max_holdings(self) -> int:
        return 5

    @property
    def sizing_pcts(self) -> List[float]:
        return [0.30, 0.25, 0.20, 0.15, 0.10]

    def _all_tickers(self, engine) -> List[str]:
        with engine.connect() as conn:
            res = conn.execute(text(
                "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"
            ))
            skip = {
                "stock_metadata", "stock_financials_quarterly", "stock_financials_yearly",
                "xlb", "xlc", "xle", "xlf", "xli", "xlk", "xlp", "xlre", "xlu", "xlv", "xly",
            }
            return [row[0] for row in res if row[0] not in skip]

    def _build_cfg(self, as_of_date: str):
        """Build a fresh StrategyConfig for as_of_date."""
        if "build_config" in self._mod and callable(self._mod["build_config"]):
            return self._mod["build_config"](as_of=as_of_date)
        if "CONFIG" in self._mod and self._mod["CONFIG"] is not None:
            cfg = self._mod["CONFIG"]
            cfg.as_of = as_of_date
            return cfg
        raise RuntimeError("User strategy has no build_config() or CONFIG")

    def get_signals(self, as_of_date: str, engine) -> List[Signal]:
        """Compute candidate signals for as_of_date.

        Implementation: call the user's precompute + entry_score on the
        full universe, return the top max_holdings as Signals.
        """
        cfg = self._build_cfg(as_of_date)
        start_date = (as_of_date[:4] + "-01-01")
        tickers = self._all_tickers(engine)
        stock_db = self._mod["precompute"](tickers, start_date, as_of_date)

        caps = [v.get("market_cap", 0) for v in stock_db.values() if v.get("market_cap", 0) > 0]
        cap_max = max(caps) if caps else 1
        cap_min = min(caps) if caps else 0
        cap_range = cap_max - cap_min if cap_max > cap_min else 1
        market_cap_stats = {"cap_min": cap_min, "cap_max": cap_max, "cap_range": cap_range}

        candidates = []
        for ticker, data in stock_db.items():
            for co in data.get("crossovers", []):
                if co.get("death_cross"):
                    continue
                if co.get("date") != as_of_date:
                    continue
                if co.get("volatility", 0) > cfg.max_volatility:
                    continue
                candidates.append({
                    "ticker": ticker,
                    "angle": co.get("angle", 0),
                    "market_cap": data.get("market_cap", 0),
                    "price": co.get("price", 0),
                    "sector": data.get("sector", "Unknown"),
                    "volume_ratio": co.get("volume_ratio", 0),
                })

        for c in candidates:
            c["score"] = self._mod["entry_score"](c, market_cap_stats)
        candidates.sort(key=lambda x: x["score"], reverse=True)
        top = candidates[:self.max_holdings]

        return [
            Signal(
                ticker=c["ticker"],
                side="long",
                score=c["score"],
                angle=c.get("angle", 0),
                price=c["price"],
                entry_date=as_of_date,
                entry_type="ai_strategy_builder",
            )
            for c in top
        ]

    def should_exit(self, ticker: str, as_of_date: str, engine, side: str = "long") -> ExitCheck:
        """Delegate to the user's exit_check function."""
        cfg = self._build_cfg(as_of_date)
        start_date = (as_of_date[:4] + "-01-01")
        tickers = self._all_tickers(engine)
        stock_db = self._mod["precompute"](tickers, start_date, as_of_date)
        holding = {"entry_date": as_of_date, "entry_price": 0, "peak_price": 0}
        reason = self._mod["exit_check"](ticker, as_of_date, holding, stock_db)
        if reason is None:
            return ExitCheck(should_close=False, reason="")
        return ExitCheck(should_close=True, reason=reason)
